/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#5def8f",
        "tertiary-fixed-dim": "#ff7986",
        "on-tertiary": "#490010",
        "tertiary-container": "#fc4563",
        "error-container": "#9f0519",
        "error": "#ff716c",
        "tertiary-dim": "#ff6f7e",
        "primary": "#69daff",
        "outline-variant": "#40485d",
        "inverse-primary": "#006880",
        "primary-fixed": "#00cffc",
        "on-secondary-container": "#e3ffe4",
        "surface-container-lowest": "#000000",
        "on-secondary-fixed": "#004a22",
        "on-tertiary-fixed-variant": "#780021",
        "secondary": "#6dfe9c",
        "on-primary-container": "#004050",
        "surface-bright": "#1f2b49",
        "on-primary-fixed": "#002a35",
        "inverse-on-surface": "#4d556b",
        "background": "#060e20",
        "on-primary-fixed-variant": "#004a5c",
        "secondary-dim": "#5def8f",
        "primary-dim": "#00c0ea",
        "on-secondary": "#005f2e",
        "on-error-container": "#ffa8a3",
        "inverse-surface": "#faf8ff",
        "secondary-container": "#006d36",
        "on-background": "#dee5ff",
        "surface-container-high": "#141f38",
        "on-surface-variant": "#a3aac4",
        "on-secondary-fixed-variant": "#006a34",
        "tertiary-fixed": "#ff9099",
        "surface-variant": "#192540",
        "tertiary": "#ff6f7e",
        "surface-container": "#0f1930",
        "primary-fixed-dim": "#00c0ea",
        "outline": "#6d758c",
        "on-tertiary-container": "#100001",
        "error-dim": "#d7383b",
        "on-primary": "#004a5d",
        "surface-container-low": "#091328",
        "secondary-fixed": "#6dfe9c",
        "surface": "#060e20",
        "primary-container": "#00cffc",
        "on-error": "#490006",
        "surface-container-highest": "#192540",
        "on-tertiary-fixed": "#39000b",
        "surface-dim": "#060e20",
        "on-surface": "#dee5ff",
        "surface-tint": "#69daff"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
